#!/bin/bash
# PostgreSQL Database Initialization Script for IoT Edge Computing Project

set -e  # Exit on error

echo "🔧 Setting up PostgreSQL database for IoT Edge Computing..."

# Database configuration
DB_NAME="edgedevices"
DB_USER="iot_user"
DB_PASSWORD="iot_pass_2026"  # Change this to a secure password

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Step 1: Dropping existing database/user if they exist...${NC}"
sudo -u postgres psql <<EOF
DROP DATABASE IF EXISTS $DB_NAME;
DROP USER IF EXISTS $DB_USER;
EOF

echo -e "${GREEN}✓ Cleaned up existing resources${NC}"

echo -e "${YELLOW}Step 2: Creating database and user...${NC}"
sudo -u postgres psql <<EOF
CREATE DATABASE $DB_NAME;
CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;

-- Connect to the new database and grant schema privileges
\c $DB_NAME
GRANT ALL ON SCHEMA public TO $DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DB_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DB_USER;
EOF

echo -e "${GREEN}✓ Database '$DB_NAME' and user '$DB_USER' created${NC}"

echo -e "${YELLOW}Step 3: Initializing schema...${NC}"
sudo -u postgres psql -d $DB_NAME -f "$(dirname "$0")/schema.sql"

echo -e "${GREEN}✓ Schema initialized successfully${NC}"

echo -e "${YELLOW}Step 4: Creating .env file...${NC}"
cat > "$(dirname "$0")/.env" <<EOF
# PostgreSQL Database Configuration
# Auto-generated by init_db.sh on $(date)

DB_HOST=localhost
DB_PORT=5432
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
EOF

chmod 600 "$(dirname "$0")/.env"  # Restrict permissions to owner only
echo -e "${GREEN}✓ .env file created with secure permissions (600)${NC}"

echo -e "${YELLOW}Step 5: Verifying setup...${NC}"
sudo -u postgres psql -d $DB_NAME -c "\dt"

echo ""
echo -e "${GREEN}🎉 Database setup complete!${NC}"
echo ""
echo "Database Configuration:"
echo "  DB_NAME: $DB_NAME"
echo "  DB_USER: $DB_USER"
echo "  DB_PASSWORD: $DB_PASSWORD"
echo ""
echo -e "${GREEN}Credentials saved to: server/.env${NC}"
echo -e "${YELLOW}IMPORTANT: .env is gitignored - it will NOT be committed to version control${NC}"
echo ""
echo "To start the Flask server:"
echo "  cd server"
echo "  python app.py"
